const base = document.body.dataset.base, csrf = base.split('/').pop();
let language = document.documentElement.lang === 'zh' ? 'zh' : 'en', latest;
const words = {
  en: { title: 'Your phone, connected.', intro: 'Keep your phone and computer on the same private Wi-Fi or Ethernet network.', stepTitle: 'Scan once. Connect again anytime.', steps: 'Open PhoneBridge on Android. Tap “Scan to pair”, scan this code, then confirm on your phone.', privacy: 'This private QR contains your pairing key. Keep it on your computer. Your phone controls accessibility and action permissions.', download: 'Download the Android app ↗', start: 'Start desktop service', networkTitle: 'Choose another computer network', networkHelp: 'We choose an active private network automatically. Disconnect the phone before changing networks. Existing managed services must be stopped first.', change: 'Use this network', footer: 'PhoneBridge 0.6.0 · Runs locally · Default access is read-only', connected: 'Phone connected', waiting: 'Ready · Waiting for your phone', offline: 'Desktop service unavailable', failure: 'Could not reach the local client. Reopen PhoneBridge.' },
  zh: { title: '连接你的手机。', intro: '让手机和电脑连接到同一个私人 Wi-Fi 或以太网。', stepTitle: '扫码一次，下次直接连接。', steps: '打开 Android 上的 PhoneBridge，点击「扫码配对」，扫描二维码，然后在手机上确认。', privacy: '这是包含配对密钥的私人二维码，请留在电脑上。无障碍权限和操作开关始终由你在手机上确认。', download: '下载 Android 应用 ↗', start: '启动电脑端服务', networkTitle: '选择其他电脑网络', networkHelp: '我们自动选择可用的私人网络。更换网络前请先断开手机；已有托管服务需要先停止。', change: '使用这个网络', footer: 'PhoneBridge 0.6.0 · 本地运行 · 默认只读', connected: '手机已连接', waiting: '服务就绪 · 等待手机连接', offline: '电脑端服务暂不可用', failure: '无法连接本地客户端，请重新打开 PhoneBridge。' }
};
Object.assign(words.en,{aiTitle:'Connect AI',aiHelp:'Add this stdio MCP configuration in an AI client that supports MCP. It uses the installed runtime and your saved pairing identity. Pair your phone first; action permission stays on the phone.',copyMcp:'Copy MCP configuration',copied:'Configuration copied. Add it to your AI client’s MCP settings.',copyFailed:'Copy unavailable. Select and copy the configuration below.'});
Object.assign(words.zh,{aiTitle:'连接 AI',aiHelp:'在支持 MCP 的 AI 客户端中添加这份 stdio 配置。它使用已安装的运行时和保存的配对身份。请先连接手机；操作授权仍由你在手机上开启。',copyMcp:'复制 MCP 配置',copied:'配置已复制，请添加到 AI 客户端的 MCP 设置。',copyFailed:'无法自动复制，请选中下方配置并复制。'});
Object.assign(words.en,{lanTitle:'Phone cannot connect?',lanHelp:'Windows may have blocked the installed runtime. Approve the Windows owner prompt to allow only this TCP port on Private networks from your local subnet. Your firewall stays enabled; phone permissions stay on your phone.',allowLan:'Allow LAN connection',lanApproved:'LAN permission granted. Retry connecting on your phone.',lanPending:'Waiting for Windows owner approval…'});
Object.assign(words.zh,{lanTitle:'手机无法连接？',lanHelp:'Windows 可能阻止了已安装的运行时。确认 Windows 的所有者提示后，仅允许当前 TCP 端口在专用网络中接收本地子网连接。防火墙保持开启；手机权限仍由你在手机上设置。',allowLan:'允许局域网连接',lanApproved:'已允许局域网连接，请在手机上重试连接。',lanPending:'等待 Windows 所有者确认…'});
function render() { const w = words[language]; document.documentElement.lang = language; for (const key of ['title','intro','stepTitle','steps','privacy','download','start','networkTitle','networkHelp','change','footer','aiTitle','aiHelp','copyMcp','lanTitle','lanHelp','allowLan']) document.getElementById(key).textContent = w[key]; if (latest) document.getElementById('status').textContent = latest.unavailable ? w.offline : latest.connected ? w.connected : w.waiting; }
async function refresh() { try { const r = await fetch(base + '/status'); if (!r.ok) throw new Error(); latest = await r.json(); document.getElementById('qr').src = latest.qr; document.getElementById('mcpConfig').textContent = JSON.stringify(latest.mcpConfiguration,null,2); document.getElementById('address').textContent = `${latest.name} · ${latest.address}:${latest.port}`; const select = document.getElementById('networks'); const selected = select.value || latest.address; select.replaceChildren(...latest.networks.map(n => { const option = document.createElement('option'); option.value = n.address; option.textContent = `${n.name} · ${n.address}`; return option; })); select.value = selected; render(); } catch { document.getElementById('error').textContent = words[language].failure; } }
async function mutate(route, body) { const error = document.getElementById('error'); error.textContent = ''; try { const r = await fetch(base + route, { method: 'POST', headers: { 'X-PhoneBridge-CSRF': csrf, 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined }); const result = await r.json(); if (!r.ok) throw new Error(result.error); await refresh();return true; } catch (e) { error.textContent = e.message;return false; } }
document.getElementById('language').onclick = () => { language = language === 'en' ? 'zh' : 'en'; render(); };
document.getElementById('start').onclick = () => mutate('/start');
document.getElementById('change').onclick = () => mutate('/network', { address: document.getElementById('networks').value });
document.getElementById('allowLan').onclick = async () => { const button=document.getElementById('allowLan'),status=document.getElementById('lanStatus');button.disabled=true;status.textContent=words[language].lanPending;try{status.textContent=await mutate('/allow-lan')?words[language].lanApproved:'';}finally{button.disabled=false;} };
document.getElementById('copyMcp').onclick = async () => { const status=document.getElementById('copyStatus');try{if(!latest?.mcpConfiguration)throw new Error();await navigator.clipboard.writeText(JSON.stringify(latest.mcpConfiguration,null,2));status.textContent=words[language].copied;}catch{status.textContent=words[language].copyFailed;const selection=window.getSelection();selection.removeAllRanges();const range=document.createRange();range.selectNodeContents(document.getElementById('mcpConfig'));selection.addRange(range);} };
render(); refresh(); setInterval(refresh, 2500);
